[sqlbalanser]
# ectd, haproxy
haproxy ansible_host=192.168.0.198

[web]
nginx ansible_host=192.168.0.199

[dbservers]
pgMaster ansible_host=192.168.0.150
pgSlaveOne ansible_host=192.168.0.151
pgSlaveTwo ansible_host=192.168.0.152

[backend]
# uvicorn 
backendOne ansible_host=192.168.0.202

[frontend]
# nginx, react
frontendOne ansible_host=192.168.0.201

[redis]
# redis as cashe
rediscache ansible_host=192.168.0.210

[post_notification]
# post notification websocket
notification_post ansible_host=192.168.0.212

[post_consumer]
# post rabbitMQ consumer
consumer_post ansible_host=192.168.0.212

[rebbitmqservers]
# mongoDB OS Router
rabbitmq ansible_host=192.168.0.212

[dialogServers]
# servers Dialogs service
dialogServer ansible_host=192.168.0.212

[mongoconfigservers]
# mongoDB Config server
mongoconfig ansible_host=192.168.0.212

[mongoshardservers]
# mongoDB Shard server
mongoshard ansible_host=192.168.0.212

[mongorouterservers]
# mongoDB OS Router
mongoos ansible_host=192.168.0.212

[mongocluster:children]
mongoconfigservers
mongoshardservers
mongorouterservers


[app:children]
backend
frontend
dialogServers

[all:vars]
ansible_connection=ssh
ansible_user=rudik
ansible_port=22