[dbservers]
pgMaster ansible_host=192.168.0.150
pgSlaveOne ansible_host=192.168.0.151
pgSlaveTwo ansible_host=192.168.0.152

[backend]
# uvicorn 
backendOne ansible_host=192.168.0.202

[frontend]
# nginx, react
frontendOne ansible_host=192.168.0.201

[app:children]
backend
frontend

[all:vars]
ansible_connection=ssh
ansible_user=rudik
ansible_port=22