[dbservers]
pg_master ansible_host=192.168.0.150
pg_slave_one ansible_host=192.168.0.151
pg_slave_two ansible_host=192.168.0.152

[backend]
# uvicorn 
back_one ansible_host=192.168.0.202

[frontend]
# nginx, react
front_one ansible_host=192.168.0.201


[all:vars]
ansible_connection=ssh
ansible_user=rudik
ansible_port=22