---
# Service for deploy
deploy_services:
  - name: postgres
    version: latest
  - name: app_backend
    version: latest
  - name: app_frontend
    version: latest
  - name: app_notification
    version: latest
  - name: app_post_consumer
    version: latest
  - name: nginx
    version: latest
  - name: redis_cache
    version: latest

# Service for build
build_services:
  - name: postgres
    version: latest
  - name: app_backend
    version: latest
  - name: app_frontend
    version: latest
  - name: app_notification
    version: latest
  - name: app_post_consumer
    version: latest
  - name: nginx
    version: latest

# Monitoring
monitoring_services:
  - name: zabbix-agent-app
    version: latest
  - name: zabbix-agent-db
    version: latest
  
# Default zabbix agent image
monitoring_images:
  - name: zabbix-agent
  - version: latest

# HA postgres cluster ["HaProxy", "ETCD", "Patrony"]
pd_cluster:
  - name: haproxy
    version: latest
  - name: etcd
    version: 3.5.21

# HA mongoDB cluster ["Shard", "Config", "MongoOS"]
mongodb_cluster:
  - image: mongodb
    name: mongo-config-server
    version: latest
  - image: mongodb
    name: mongo-shard-server
    version: latest
  - image: mongodb
    name: mongo-os-router
    version: latest

mongo_config_servers:
  - image: mongo:4.4.18
    name: mongoConfigSrvOne
    port: 10001
  - image: mongo:4.4.18
    name: mongoConfigSrvTwo
    port: 10002
  - image: mongo:4.4.18
    name: mongoConfigSrThree
    port: 10003

mongo_shard_servers:
  - image: mongo:4.4.18
    name: mongoShardSrvOne
    port: 20001
  - image: mongo:4.4.18
    name: mongoShardSrvTwo
    port: 20002
  - image: mongo:4.4.18
    name: mongoShardSrThree
    port: 20003

mongo_os_servers:
  - image: mongo:4.4.18
    name: mongoOSSrvOne
    port: 30001

rabbitmq_server:
  - name: rabbitmq
    version: 3.10.7-management


# Vars for database # default home catalog
db_path: /home/rudik/base-data
sql_pach: /home/rudik/base-init

db_env:
  db_base: api
  password: "{{ postgres.password }}"
  user: "{{ postgres.user }}"

redis_env:
  redis_db: "{{ redis_cache }}"

rabbit_mq_env:
  user: "{{ rabbit_mq.user }}"
  password: "{{ rabbit_mq.password }}"
  queue: "{{ rabbit_mq.queue }}"
  routing_key: "{{ rabbit_mq.routing_key }}"

  #radis_cache:
  #user: admin
  #password: admin
  #db_name: 0

# Var for api service 
app_backend_env:
  - name: DB_HOST
  # Take ip from inventory
    value: 192.168.0.198
  - name: DB_PORT_READ
    value: 5001
  - name: DB_PORT_WRITE
    value: 5000
  - name: DB_NAME
    value: "{{ db_env.db_base }}"
  - name: DB_USER
    value: "{{ db_env.user }}"
  - name: DB_PASSWORD
    value: "{{ db_env.password }}"
  - name: SECRET_KEY
    value: "{{ app.key }}"
  - name: ALGORITHM
    value: HS256
  - name: REDIS_CACHE_HOST
    value: 192.168.0.210
  - name: REDIS_CACHE_LOGIN
    value: "{{ redis_cache.user }}"
  - name: REDIS_CACHE_PORT
    value: 6380
  - name: REDIS_PASSWORD
    value: "{{ redis_cache.password }}"
  - name: REDIS_DB
    value: "{{ redis_cache.db_name }}"
  - name: MONGODB_HOST
    value: 192.168.0.212
  - name: MONGODB_PORT
    value: 30001
  - name: MONGODB_DB
    value:  messages
  - name: MONGODB_COLLECTIONS
    value: from_to
  - name: POST_NOTIFICATION_HOST
    value: 192.168.0.212
  - name: POST_NOTIFICATION_PORT
    value: 8001
  - name: RABBITMQ_HOST
    value: 192.168.0.212
  - name: RABBITMQ_PORT
    value: 5672
  - name: RABBITMQ_USER
    value: "{{ rabbit_mq_env.user }}"
  - name: RABBITMQ_PASSWORD
    value: "{{ rabbit_mq_env.password }}"
  - name: RABBITMQ_QUEUE
    value: "{{ rabbit_mq_env.queue }}"
  - name: RABBITMQ_ROUTER_KEY
    value: "{{ rabbit_mq_env.routing_key }}"


# Var to repository user home catalog
git_pach: /home/rudik/repository

# Default directory to build images zabbix agent postgres
def_path: /home/rudik/src

# Default directory to build image for postgres/patroni
patroni_path: /home/rudik/patroni

# User name
user_name: rudik

# For zabbix agent
zabbix_server: 192.168.0.250