---
# Service for deploy
deploy_services:
  - name: postgres
    version: 12.20-alpine
  - name: app_backend
    version: latest
  - name: app_frontend
    version: latest

build_services:
  - name: postgres
    version: 12.20-alpine
  - name: app_backend
    version: latest
  - name: app_frontend
    version: latest

# Vars for database # default home catalog
db_path: /home/rudik/base-data
sql_pach: /home/rudik/base-init

db_env:
  db_base: api
  password: "{{ postgres.password }}"
  user: "{{ postgres.user }}"


# Var for api service 
app_backend_env:
  - name: DB_HOST
  # Take ip from inventory
    value: 192.168.0.150
  - name: DB_PORT
    value: 5432
  - name: DB_NAME
    value: "{{ db_env.db_base }}"
  - name: DB_USER
    value: "{{ db_env.user }}"
  - name: DB_PASSWORD
    value: "{{ db_env.password }}"
  - name: SECRET_KEY
    value: "{{ app.key }}"
  - name: ALGORITHM
    value: HS256

# Var to repository user home catalog
git_pach: /home/rudik/repository

# User name
user_name: rudik
