---
# Service for deploy
services:
  - name: postgres
    version: 12.20-alpine
  - name: app
    version: latest

build_services:
  - name: app
    version: latest


# Vars for database
db_path: /var/base-data
sql_pach: /var/base-init

db_env:
  db_base: api
  password: "{{ postgres.password }}"
  user: "{{ postgres.user }}"


# Var for api service 
app_env:
  - name: DB_HOST
    value: 192.168.0.120
  - name: DB_PORT
    value: 5432
  - name: DB_NAME
    value: "{{ db_env.db_base }}"
  - name: DB_USER
    value: "{{ db_env.user }}"
  - name: DB_PASSWORD
    value: "{{ db_env.password }}"
  - name: SECRET_KEY
    value: "{{ app.key }}"
  - name: ALGORITHM
    value: HS256

# Var to repository
git_pach: ~/repository
