---
# Service for deploy
deploy_services:
  - name: postgres
    version: latest
  - name: app_backend
    version: latest
  - name: app_frontend
    version: latest
  - name: nginx
    version: latest

# Service for build
build_services:
  - name: postgres
    version: latest
  - name: app_backend
    version: latest
  - name: app_frontend
    version: latest
  - name: nginx
    version: latest

# Monitoring
monitoring_services:
  - name: zabbix-agent-app
    version: latest
  - name: zabbix-agent-db
    version: latest
  
# Default zabbix agent image
monitoring_images:
  - name: zabbix-agent
  - version: latest

# HA postgres cluster ["HaProxy", "ETCD", "Patrony"]
pd_cluster:
  - name: haproxy
    version: latest
  - name: etcd
    version: 3.5.21

# Vars for database # default home catalog
db_path: /home/rudik/base-data
sql_pach: /home/rudik/base-init

db_env:
  db_base: api
  password: "{{ postgres.password }}"
  user: "{{ postgres.user }}"


# Var for api service 
app_backend_env:
  - name: DB_HOST
  # Take ip from inventory
    value: 192.168.0.198
  - name: DB_PORT_READ
    value: 5001
  - name: DB_PORT_WRITE
    value: 5000
  - name: DB_NAME
    value: "{{ db_env.db_base }}"
  - name: DB_USER
    value: "{{ db_env.user }}"
  - name: DB_PASSWORD
    value: "{{ db_env.password }}"
  - name: SECRET_KEY
    value: "{{ app.key }}"
  - name: ALGORITHM
    value: HS256

# Var to repository user home catalog
git_pach: /home/rudik/repository

# Default directory to build images zabbix agent postgres
def_path: /home/rudik/src

# Default directory to build image for postgres/patroni
patroni_path: /home/rudik/patroni

# User name
user_name: rudik

# For zabbix agent
zabbix_server: 192.168.0.250