---
postgres:
  user: admin
  password: admin

redis_cache:
  user: admin
  password: admin
  db_name: 0

mondo_db:
  db: messages
  collections: from_to

app:
  key: api-key

zabbix_agent_db:
  user: zbx_monitor
  password: zbx_monitor