---
- block:
  - name: "Deploy service -> [{{ name }}]"
    ansible.builtin.docker_container:
      name: "{{ name }}"
      image: "{{ name }}"
      recreate: true
      ports:
        - "8000:8000"
      hostname: "{{ name }}"
      restart_policy: unless-stopped
      volumes:
        - "{{ git_pach }}/default.conf:/etc/nginx/conf.d/default.conf:ro"

  - name: Include task -> remove docker images
    ansible.builtin.include_tasks:
      file: ./common_task/remove_untagged_images.yml
      
  when: 
    - inventory_hostname in groups["web"]
  tags: "{{ name }}"