---
- name: Set Hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Set timezone
  community.general.timezone:
    name: Europe/Moscow

- name: Set 24 format time
  command: "localectl set-locale LC_TIME='en_GB.UTF-8'"