---
- block:
  - name: Include host
    ansible.builtin.include_tasks:
      file: host.yml

  - name: Include docker
    ansible.builtin.include_tasks:
      file: docker.yml

  - name: Include db
    ansible.builtin.include_tasks:
      file: db.yml
  
  become: true